//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPorjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int ID { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<int> Yıl { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string Plaka { get; set; }
        public string Renk { get; set; }
        public Nullable<int> km { get; set; }
        public string YakıtTipi { get; set; }
        public string VitesTipi { get; set; }
        public string Durum { get; set; }
        public string PhotoPath { get; set; }
    }
}
